loadstring(game:HttpGet("https://raw.githubusercontent.com/FabJheiny/Scripts/refs/heads/main/next.ui"))()

Library:Register({
    Name        = "Calculator",
    Category    = "Movement",
    Icon        = "🔢",
    Description = "Só uma calculadora normal",
    Load        = function()
        loadstring(game:HttpGet("https://raw.githubusercontent.com/you/repo/main/speed_bypass.lua"))()
    end
})
